version: "3.5"

services:

  proxy:
    container_name: jamfactory_proxy
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/templates
    environment:
      JAM_BACKEND_ADDRESS: backend:3000
      JAM_STATIC_ADDRESS: static:9000
      JAM_WEB_ADDRESS: web:4200

  backend:
    container_name: jamfactory_backend
    build: ${JAM_BACKEND_PATH}
    env_file: .env
    environment:
      JAM_DATA_DIR: /data
      JAM_REDIS_ADDRESS: redis:6379
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    ports:
      - "3000:3000"
    volumes:
      - "jam-data:/data"
    depends_on:
      - redis
    tty: true

  redis:
    container_name: jamfactory_redis
    image: redis:latest
    command: redis-server /etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
      - "./redis:/etc/redis/"

  web:
    container_name: jamfactory_web
    command: "npm run start -- --host 0.0.0.0 --poll 1000 --deploy-url /jam/"
    build: ${JAM_WEB_PATH}
    ports:
      - "4200:4200"
    volumes:
      - ${JAM_WEB_PATH}/src:/app/src
    environment:
      TERM: xterm-256color
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    tty: true


  static:
    container_name: jamfactory_static
    build:
      context: ${JAM_STATIC_PATH}
    ports:
      - "9000:9000"
    volumes:
      - ${JAM_STATIC_PATH}:/app
    environment:
      TERM: xterm-256color
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    tty: true

volumes:
  jam-data:
  redis-data:
