version: "3.5"

services:

  proxy:
    container_name: jamfactory_proxy
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/templates
    environment:
      JAM_BACKEND_ADDRESS: backend:3000
      JAM_STATIC_ADDRESS: static:80
      JAM_WEB_ADDRESS: web:80
    depends_on:
      - backend
      - redis
      - web
      - static

  backend:
    container_name: jamfactory_backend
    image: ghcr.io/jamfactoryapp/jamfactory-backend:latest
    env_file: .env
    environment:
      JAM_DATA_DIR: /data
      JAM_REDIS_ADDRESS: redis:6379
    volumes:
      - "jam-data:/data"
    restart: always
    depends_on:
      - redis

  redis:
    container_name: jamfactory_redis
    image: redis:latest
    command: redis-server /etc/redis/redis.conf
    restart: always
    volumes:
      - "redis-data:/data"
      - "./redis:/etc/redis/"

  web:
    container_name: jamfactory_web
    image: ghcr.io/jamfactoryapp/jamfactory-web:latest
    restart: always

  static:
    container_name: jamfactory_static
    image: ghcr.io/jamfactoryapp/jamfactory-static:latest
    volumes:
      - "./import:/usr/share/nginx/html/import"
    restart: always

volumes:
  jam-data:
  redis-data:
