version: "3.5"

services:

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/templates
    environment:
      JAM_BACKEND_ADDRESS: backend:3000
      JAM_STATIC_ADDRESS: static:9000
      JAM_WEB_ADDRESS: web:4200

  backend:
    build: ${JAM_BACKEND_PATH}
    env_file: ${JAM_BACKEND_PATH}/.env
    environment:
      JAM_DATA_DIR: /data
      JAM_REDIS_ADDRESS: redis:6379
    ports:
      - "3000:3000"
    volumes:
      - "jam-data:/data"
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: redis-server /etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
      - "./redis:/etc/redis/"

  web:
    build: ${JAM_WEB_PATH}
    ports:
      - "4200:4200"
    volumes:
      - ${JAM_WEB_PATH}/src:/app/src

  static:
    build:
      context: ${JAM_STATIC_PATH}
    ports:
      - "9000:9000"
    volumes:
      - ${JAM_STATIC_PATH}/src:/app/src

volumes:
  jam-data:
  redis-data:
